export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';



export const SET_DATE = 'SET_DATE';
export const RESET_DATE = 'RESET_DATE';



export const ADD_TASK_SAGA = 'ADD_TASK_SAGA';
export const ADD_TASK_REDUCER = 'ADD_TASK_REDUCER';

export const EDIT_TASK_SAGA = 'EDIT_TASK_SAGA';
export const EDIT_TASK_REDUCER = 'EDIT_TASK_REDUCER';

export const DELETE_TASK_SAGA = 'DELETE_TASK_SAGA';
export const DELETE_TASK_REDUCER = 'DELETE_TASK_REDUCER';

export const GET_TASKS_SAGA = 'GET_TASKS_SAGA';
export const GET_TASKS_REDUCER = 'GET_TASKS_REDUCER';



export const DO_SOMETHING = 'DO_SOMETHING';